# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.ssh.password = 'vagrant' #define password for the machine
    web.vm.box = "ubuntu/trusty64" #define the os box 
    web.vm.hostname = 'web' #define name of the machine
    web.vm.box_url = "ubuntu/trusty64"

    web.vm.network :private_network, ip: "192.168.56.101" #define ip 
    web.vm.synced_folder "./ansible", "/home/vagrant" #to run ansible-playbook loadbalancer.yml from a shared folder 
	
	web.vm.box_check_update = false
	
    web.vm.provision "shell", privileged: false, inline: <<-SHELL
            # Install Ansible
            sudo add-apt-repository ppa:ansible/ansible
            sudo apt-get update
            sudo apt-get install -y ansible

        SHELL
    web.vm.provision "ansible_local" do |ansible|
        ansible.extra_vars = { ansible_ssh_pass: 'vagrant' }
        ansible.playbook = "/home/vagrant/loadbalancer.yml"
        ansible.provisioning_path = "/home/vagrant/"
    end

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web"]
    end
  end

  config.vm.define "web1" do |web1|
    web1.ssh.password = 'vagrant'
    web1.vm.box = "ubuntu/trusty64"
    web1.vm.hostname = 'web1'
    web1.vm.box_url = "ubuntu/trusty64"

    web1.vm.network :private_network, ip: "192.168.56.102"
    web1.vm.synced_folder "./ansible", "/home/vagrant"
	
		web1.vm.box_check_update = false

    web1.vm.provision "shell", privileged: false, inline: <<-SHELL
            # Install Ansible
            sudo add-apt-repository ppa:ansible/ansible
            sudo apt-get update
            sudo apt-get install -y ansible

        SHELL
    web1.vm.provision "ansible_local" do |ansible|
        ansible.extra_vars = { ansible_ssh_pass: 'vagrant' }
        ansible.playbook = "/home/vagrant/webservers.yml"
        ansible.provisioning_path = "/home/vagrant/"
    end
	
	

    web1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web1"]
    end
  end

  config.vm.define "web2" do |web2|
    web2.ssh.password = 'vagrant'
    web2.vm.box = "ubuntu/trusty64"
    web2.vm.hostname = 'web2'
    web2.vm.box_url = "ubuntu/trusty64"

    web2.vm.network :private_network, ip: "192.168.56.103"
    web2.vm.synced_folder "./ansible", "/home/vagrant"
	
		web2.vm.box_check_update = false


    web2.vm.provision "shell", privileged: false, inline: <<-SHELL
            # Install Ansible
            sudo add-apt-repository ppa:ansible/ansible
            sudo apt-get update
            sudo apt-get install -y ansible

        SHELL

    web2.vm.provision "ansible_local" do |ansible|
        ansible.extra_vars = { ansible_ssh_pass: 'vagrant' }
        ansible.playbook = "/home/vagrant/webservers.yml"
        ansible.provisioning_path = "/home/vagrant/"
    end

    web2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web2"]
    end
  end
end
